# Generated by Django 6.0.2 on 2026-02-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
                ('application_link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
