# Generated by Django 6.0.2 on 2026-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application_link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='job',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Banking', 'Banking'), ('State Govt', 'State Govt')], max_length=50),
        ),
    ]
