# Generated by Django 6.0.2 on 2026-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_application_link_remove_job_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Banking', 'Banking'), ('State Govt', 'State Govt'), ('Defence', 'Defence')], max_length=50),
        ),
    ]
