# Generated by Django 6.0.2 on 2026-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_url_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Upcoming', 'Upcoming')], default='Open', max_length=20),
        ),
    ]
