# Generated by Django 6.0.2 on 2026-02-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('TS', 'Telangana'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('MH', 'Maharashtra')], max_length=50)),
                ('department', models.CharField(max_length=200)),
                ('eligibility', models.TextField()),
                ('age_limit', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('selection_process', models.TextField()),
                ('official_website', models.URLField()),
            ],
        ),
    ]
