# Generated by Django 6.0.2 on 2026-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_statejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='age_limit',
            field=models.CharField(default='18-42', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default='Any Degree', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=100),
            preserve_default=False,
        ),
    ]
