# Generated by Django 6.0.2 on 2026-02-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_age_limit_job_qualification_job_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='age_limit',
            field=models.CharField(default='18-42', max_length=50),
        ),
    ]
