# Generated by Django 6.0.2 on 2026-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_age_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statejob',
            name='education',
        ),
        migrations.AddField(
            model_name='statejob',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statejob',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statejob',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statejob',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='age_limit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statejob',
            name='age_limit',
            field=models.CharField(default='18-42', max_length=50),
        ),
    ]
