# Generated by Django 6.0.2 on 2026-02-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_statejob_education_statejob_last_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.AddField(
            model_name='statejob',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('TS', 'Telangana'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('MH', 'Maharashtra')], default=('AP', 'TS', 'TN'), max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('close', 'close'), ('deadline', 'deadline')], default='Open', max_length=20),
        ),
    ]
