# Generated by Django 6.0.2 on 2026-02-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_state_statejob_state_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='AP', max_length=100),
            preserve_default=False,
        ),
    ]
