# Generated by Django 6.0.2 on 2026-02-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateJob',
        ),
        migrations.RemoveField(
            model_name='job',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='job',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Banking', 'Banking'), ('State Govt', 'State Govt'), ('Defence', 'Defence'), ('Army', 'Army')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
