# Generated by Django 6.0.2 on 2026-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_delete_statejob_remove_job_age_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Banking', 'Banking'), ('Defence', 'Defence'), ('Army', 'Army')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Closed'), ('deadline', 'Deadline Soon')], default='open', max_length=20),
        ),
    ]
